### ISSUE TITLE
The link of pre-trained model seems to be invaild

### ISSUE THREAD

**Issue by Kami-code** [jsll/pytorch_6dof-graspnet#13]
Can somebody upload the pre-trained model again? Thanks a lot.

**Comment by jsll** [comment]
Unfortunately, it seems that the trained models have been removed from google drive. I'll see if I can get them back but I cannot promise anything.

**Comment by jsll** [comment]
@Kami-code I found the pre-trained models and updated the links in the repository. If you have the opportunity, could you try these out and close this issue if successful?

**Comment by Kami-code** [comment]
Thank you very much! I 've downloaded it.
