### ISSUE TITLE
Can not download the pre-trained model

### ISSUE THREAD

**Issue by BackpackPrince** [jsll/pytorch_6dof-graspnet#4]
Hello, your work is brilliant, and I have encountered an error when I try to download the pre-trained model, the Google Drive suggests that the file has been moved to your trash, I will appreciate it if you could get the file back.

**Comment by jsll** [comment]
Thanks for telling me about this issue. I have now restored the folder and the models can be downloaded again.

**Comment by richardrl** [comment]
Hey @jsll , looks like the file has been removed from the google drive, can you check this again?

**Comment by jsll** [comment]
Thanks for letting me know. I fixed the links according to https://github.com/jsll/pytorch_6dof-graspnet/issues/13.
