### ISSUE TITLE
no module named 'pointnet2-ops'

### ISSUE THREAD

**Issue by BackpackPrince** [jsll/pytorch_6dof-graspnet#5]
I got this error when I try to run 'train.py':
No module named 'pointnet2-ops'.   
I realized that this module is linked to PointNet++,  but I still do not know how to install the module after browsing the PointNet++ repo.

**Comment by jsll** [comment]
Did you install this https://github.com/erikwijmans/Pointnet2_PyTorch?

**Comment by BackpackPrince** [comment]
No,  I just realized that I did not follow your instructions exactly. Problem solved. Thank you for your reply.

**Comment by madinwei** [comment]
@BackpackPrince , if possible can you share with me how did you install pointnet++, I want to install it in windows, if you have any instruction or idea can you share it with me

**Comment by bdlim99** [comment]
@madinwei Maybe the Pointnet2 repository would not support Windows. In below issue which is posted in Pointnet2 repository, erikwijmans said that he did not test the build on Windows.
